{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5a0ca999-16a5-4c30-9b92-fd7ad0478463",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Ql. What is an Exception in python? Write the difference between Exceptions and Syntax errors.\n",
    "\n",
    "#Ans. Errors which are detected during excutions are known as Exception.\n",
    "\n",
    "#Exceptions errors:\n",
    "#Errors which occurs after passing syntax test they are also known as Logical Errors. \n",
    "\n",
    "#Syntax errors:\n",
    "#Errors which are generated by the programmers/coders not by computer."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a35c8430-710d-41ef-b4ad-d2e62266178f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q2. What happens when an exception is not handled? Explain with an example.\n",
    "\n",
    "#Ans. The exception is re-raised after the finally clause will executed when an exception is not handled.\n",
    "\n",
    "#EXAMPLE: "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bd0aff5f-c64f-4bb9-8854-a162d2aae0e8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error Detected\n"
     ]
    }
   ],
   "source": [
    "#Q3. Which Python statements are used to catch and handle exceptions? Explain with an example.\n",
    "\n",
    "#Ans. \"try and except code blocks\" is used catch exceptions and handles Exception. The try clause contains the code that can raise an exception, while the except clause contains the code lines that handle the exception. \n",
    "\n",
    "#Example:\n",
    "try:\n",
    "  print(x)\n",
    "except:\n",
    "  print(\"Error Detected\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "5490966c-b9a9-45aa-a913-16a3369f4a5f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Please check,Something went wrong\n",
      "Finished No Error Found\n"
     ]
    }
   ],
   "source": [
    "#Q4. Explain with an example:\n",
    "\n",
    "#a. try and else - try block lets you test a block of code for errors and else block lets you execute code when there is no error.\n",
    "#b. finally - finally block lets you execute code, regardless of the result of the try- and except blocks.\n",
    "#c. raise - raose block lets to throw an exceptionabs\n",
    "\n",
    "#Example:\n",
    "try:\n",
    "    x=-1\n",
    "except:\n",
    "    if x < 0:\n",
    "      raise Exception(\"Sorry, no numbers below zero\")\n",
    "else:\n",
    "    print(\"Please check, Something went wrong\")\n",
    "finally:\n",
    "  print(\"Finished No Error Found\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ddfff449-cdb0-4414-8136-ccfbad76e365",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('E', 'r', 'r', 'o', 'r')\n"
     ]
    }
   ],
   "source": [
    "#Q5. What are Custom Exceptions in python? Why do we need Custom Exceptions? Explain with an example.\n",
    "\n",
    "#Ans, Custom Exceptions are a class derived from built in Exception class. We need custom Exception as makes our program  easier to follow and more readable as an exception sholdn't be complicated.\n",
    "\n",
    "#EXAMPLE:\n",
    "class Contacterror(TypeError):\n",
    "    def __init__(self, arg):\n",
    "        self.args = arg\n",
    " \n",
    "try:\n",
    "    raise Contacterror(\"Error\")\n",
    " \n",
    "except Contacterror as e:\n",
    "    print(e.args)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "94699fd2-8047-4406-9eee-f4bff674044e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This is my custom exception\n"
     ]
    }
   ],
   "source": [
    "#Q6. Create a custom exception class. Use this class to handle an exception.\n",
    "\n",
    "class Custom_Exception(Exception):\n",
    "    \"\"\" my custom exception class \"\"\"\n",
    "\n",
    "\n",
    "try:\n",
    "    raise Custom_Exception('This is my custom exception')\n",
    "except Custom_Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d9a3b7e5-1c3f-4113-802c-0257230aa9f2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
